### PR TITLE
Build casacore 3.5.0 on macOS

### PR DESCRIPTION
**Pull request by ludwigschwardt**
- Build the released casacore 3.5.0.
- I had to include the casacore/casacore#1350 fix as a temporary patch. I also removed an old Python 2 patch. We should be patch-free after the next release 🙂
- Build Python bindings by default now, as I keep on forgetting to specify it. Who doesn't need it anyway? The upside is that we can now have Python-enabled bottles for the first time  🎉 
- Upgraded the Homebrew actions so that tests pass and we have bottles (ventura-intel and sonoma-arm).
- Updated `casacore-data` measures, for what it's worth.
- Advertise my nifty historical graft to make older commits visible during logs and blames.

### CODE REVIEW

**Comment by ludwigschwardt** [comment]
Still busy tweaking actions to make the tests and bottles pass :-)

**Comment by ludwigschwardt** [comment]
The tests pass again and we have bottles :-)

**Comment by ludwigschwardt** [comment]
I have tested this together with `python-casacore` on a real MS, so it works at some level... Please note that the "brew bot" suggests labelling this as `pr-pull` to complete the bottling process. More here:

https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Review by tammojan — APPROVED** [review]
Looks good to me! I have not tested the bottles on my machine.

**Comment by ludwigschwardt** [comment]
I tried the `pr-pull` approach but it is now a bit borked... The first time it succeeded to upload macOS bottles as release assets but then crashed because `main` branch was missing. The second time it did not like that the assets are already there.

I don't want to remove the release either, as it has a tag and all, so for now I'm just merging the PR like in the past.

**Pull request merged**
